
services:
  # Node app container
  app:
    build: .
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis  # Wait for Redis to be ready before starting the app
    volumes:
      - .:/app

  # Redis container
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  # Expose Redis port to the host machine
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  
  # Nginx Container
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    depends_on:
      - app